name: CI

on: [push]

permissions:
  contents: read

jobs:

  lint:

    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download

      - name: Build service
        run: make bin/service

      - name: Build mock
        run: make bin/fb_mock

  test:

    name: Test Service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: service

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v
