name: CI

on: [push]

permissions:
  contents: read

jobs:

  build_service:

    name: Build Service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: service

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: service/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v

  build_fb_mock:

    name: Build Mock
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fb_mock

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: fb_mock/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v cmd/main.go

  test:

    name: Test Service
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: service

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache-dependency-path: service/go.sum

      - name: Download dependencies
        run: go mod download

      - name: Test
        run: go test -v
